#include <cmath>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <optional>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include "pamguard/detectors/IshmaelDetector.h"

// Replays the Ishmael energy-sum fixture generated by
// IshmaelEnergySumFixtureExporter, which drives the REAL EnergySumProcess
// and IshPeakProcess end to end. Inputs are complex FFT slices per channel;
// "fn" rows are the reference's detection-function values (with noise floor
// and raw value when adaptive); "detection" rows are the picked detections
// in emission order. Pinned: the RAW-samples-vs-slice-units comparisons,
// the write-once smoothing state, the shared-across-channels noise floor,
// refractory merging, the maxTime rejection path, and the dropped
// still-open event at stream end.

namespace {

using pamguard::detectors::IshmaelDetection;
using pamguard::detectors::IshmaelDetSample;
using pamguard::detectors::IshmaelEnergySum;
using pamguard::detectors::IshmaelEnergySumConfig;
using pamguard::detectors::IshmaelPeakPicker;

std::vector<std::string> split(const std::string& line) {
    std::vector<std::string> cells;
    std::stringstream stream(line);
    std::string cell;
    while (std::getline(stream, cell, ',')) {
        cells.push_back(cell);
    }
    return cells;
}

void check_close(const std::string& context, double actual, double expected, double& max_error) {
    const double error = std::abs(actual - expected);
    const double scale = std::max(1.0, std::abs(expected));
    max_error = std::max(max_error, error / scale);
    if (error / scale > 1e-9) {
        throw std::runtime_error(context + ": " + std::to_string(actual) + " expected " +
                                 std::to_string(expected));
    }
}

} // namespace

int main(int argc, char** argv) {
    if (argc != 2) {
        std::cerr << "Usage: ishmael_fixture_check <fixture.csv>\n";
        return 2;
    }

    try {
        std::ifstream input(argv[1]);
        if (!input) {
            throw std::runtime_error(std::string("could not open fixture: ") + argv[1]);
        }

        std::optional<IshmaelEnergySum> energy;
        std::optional<IshmaelPeakPicker> picker;
        std::string case_name;
        std::size_t case_count = 0;
        std::size_t in_count = 0;
        std::size_t fn_count = 0;
        std::size_t det_count = 0;
        double max_error = 0.0;

        // One in row produces exactly one fn row; the fn row's value then
        // feeds the picker, whose optional detection is matched against the
        // detection row that follows.
        std::optional<IshmaelDetSample> fn_pending;
        std::size_t pending_channel = 0;
        std::int64_t pending_start_sample = 0;
        std::optional<IshmaelDetection> det_pending;

        auto finish_case = [&]() {
            if (fn_pending.has_value()) {
                throw std::runtime_error(case_name + ": fn value never matched");
            }
            if (det_pending.has_value()) {
                throw std::runtime_error(case_name + ": engine produced a detection the reference did not");
            }
        };

        std::string line;
        while (std::getline(input, line)) {
            while (!line.empty() && (line.back() == '\r' || line.back() == '\n')) {
                line.pop_back();
            }
            if (line.empty() || line[0] == '#') {
                continue;
            }
            const auto cells = split(line);
            if (cells[0] == "case") {
                finish_case();
                case_name = cells[1];
                const double sample_rate = std::stod(cells[2]);
                const int fft_length = std::stoi(cells[3]);
                const int fft_hop = std::stoi(cells[4]);
                IshmaelEnergySumConfig config;
                config.enabled = true;
                config.f0 = std::stod(cells[5]);
                config.f1 = std::stod(cells[6]);
                config.ratio_f0 = std::stod(cells[7]);
                config.ratio_f1 = std::stod(cells[8]);
                config.use_ratio = cells[9] == "1";
                config.use_log = cells[10] == "1";
                config.adaptive_threshold = cells[11] == "1";
                config.long_filter = std::stod(cells[12]);
                config.spike_decay = std::stod(cells[13]);
                config.output_smoothing = cells[14] == "1";
                config.short_filter = std::stod(cells[15]);
                config.thresh = std::stod(cells[16]);
                config.min_time_s = std::stod(cells[17]);
                config.max_time_s = std::stod(cells[18]);
                config.refractory_time_s = std::stod(cells[19]);
                energy.emplace(sample_rate, config);
                picker.emplace(sample_rate, static_cast<std::size_t>(fft_hop), config);
                (void)fft_length;
                ++case_count;
            }
            else if (cells[0] == "in") {
                if (det_pending.has_value()) {
                    throw std::runtime_error(case_name + ": engine produced a detection the reference did not");
                }
                pending_channel = static_cast<std::size_t>(std::stoul(cells[1]));
                pending_start_sample = std::stoll(cells[2]);
                // cells[3] is the burst flag, informational only.
                std::vector<double> magsq;
                magsq.reserve((cells.size() - 4) / 2);
                for (std::size_t i = 4; i + 1 < cells.size(); i += 2) {
                    const double re = std::stod(cells[i]);
                    const double im = std::stod(cells[i + 1]);
                    magsq.push_back(re * re + im * im);
                }
                fn_pending = energy->process_frame(magsq);
                ++in_count;
            }
            else if (cells[0] == "fn") {
                if (!fn_pending.has_value()) {
                    throw std::runtime_error(case_name + ": fn row with no processed slice");
                }
                check_close(case_name + " detValue", fn_pending->det_value, std::stod(cells[1]), max_error);
                if (cells.size() == 4) {
                    if (!fn_pending->has_noise_floor) {
                        throw std::runtime_error(case_name + ": reference reported a noise floor, engine did not");
                    }
                    check_close(case_name + " noiseFloor", fn_pending->noise_floor, std::stod(cells[2]), max_error);
                    check_close(case_name + " rawValue", fn_pending->raw_value, std::stod(cells[3]), max_error);
                }
                else if (fn_pending->has_noise_floor) {
                    throw std::runtime_error(case_name + ": engine reported a noise floor, reference did not");
                }
                det_pending = picker->process(pending_channel, pending_start_sample, fn_pending->det_value);
                fn_pending.reset();
                ++fn_count;
            }
            else if (cells[0] == "detection") {
                if (!det_pending.has_value()) {
                    throw std::runtime_error(case_name + ": engine produced no detection for a detection row");
                }
                const auto channel = static_cast<std::size_t>(std::stoul(cells[1]));
                if (det_pending->channel != channel ||
                    det_pending->start_sample != std::stoll(cells[2]) ||
                    det_pending->duration_samples != std::stoll(cells[3]) ||
                    det_pending->peak_time_sample != std::stoll(cells[4])) {
                    throw std::runtime_error(case_name + ": detection sample fields mismatch (got start " +
                                             std::to_string(det_pending->start_sample) + " expected " + cells[2] + ")");
                }
                check_close(case_name + " peakHeight", det_pending->peak_height, std::stod(cells[5]), max_error);
                if (det_pending->start_time_ms != std::stoll(cells[6])) {
                    throw std::runtime_error(case_name + ": startMsec mismatch");
                }
                check_close(case_name + " lowFreq", det_pending->low_freq_hz, std::stod(cells[7]), max_error);
                check_close(case_name + " highFreq", det_pending->high_freq_hz, std::stod(cells[8]), max_error);
                det_pending.reset();
                ++det_count;
            }
        }
        finish_case();

        std::cout << "ishmael fixture parity: cases=" << case_count << " in=" << in_count
                  << " fn=" << fn_count << " detections=" << det_count
                  << " maxRelError=" << max_error << "\n";
        return 0;
    }
    catch (const std::exception& error) {
        std::cerr << "ishmael_fixture_check failed: " << error.what() << "\n";
        return 1;
    }
}
