#include <cmath>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <optional>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include "pamguard/detectors/LtsaMonitor.h"

// Replays the LTSA fixture generated by LtsaFixtureExporter, which drives
// the REAL ltsa.LtsaProcess.ChannelProcess: inputs are complex FFT slices
// with timestamps, outputs are the completed averaging periods in emission
// order (including the flush-closed trailing period). The stream pins the
// epoch alignment of the first period, the boundary slice landing in the
// NEXT period, and closePeriod's single-interval advance after a time gap.
//
// CSV order is in-row first, then the out row it triggered, so the engine's
// produced interval is held until its out row arrives; an out row with
// nothing held is the case's trailing flush.

namespace {

using pamguard::detectors::LtsaConfig;
using pamguard::detectors::LtsaInterval;
using pamguard::detectors::LtsaMonitor;

std::vector<std::string> split(const std::string& line) {
    std::vector<std::string> cells;
    std::stringstream stream(line);
    std::string cell;
    while (std::getline(stream, cell, ',')) {
        cells.push_back(cell);
    }
    return cells;
}

} // namespace

int main(int argc, char** argv) {
    if (argc != 2) {
        std::cerr << "Usage: ltsa_fixture_check <fixture.csv>\n";
        return 2;
    }

    try {
        std::ifstream input(argv[1]);
        if (!input) {
            throw std::runtime_error(std::string("could not open fixture: ") + argv[1]);
        }

        std::optional<LtsaMonitor> monitor;
        std::optional<LtsaInterval> held;
        std::string case_name;
        std::size_t case_count = 0;
        std::size_t in_count = 0;
        std::size_t out_count = 0;
        double max_error = 0.0;

        auto check_held = [&](const std::vector<std::string>& cells) {
            if (!held.has_value()) {
                throw std::runtime_error(case_name + ": engine produced no interval for an out row");
            }
            const auto start_ms = std::stoll(cells[1]);
            const auto end_ms = std::stoll(cells[2]);
            const auto n_fft = std::stoi(cells[3]);
            const auto start_sample = std::stoll(cells[4]);
            const auto duration = std::stoll(cells[5]);
            if (held->start_time_ms != start_ms || held->end_time_ms != end_ms) {
                throw std::runtime_error(case_name + ": window [" + std::to_string(held->start_time_ms) +
                                         "," + std::to_string(held->end_time_ms) + ") expected [" +
                                         std::to_string(start_ms) + "," + std::to_string(end_ms) + ")");
            }
            if (held->n_fft != n_fft) {
                throw std::runtime_error(case_name + ": nFFT " + std::to_string(held->n_fft) +
                                         " expected " + std::to_string(n_fft));
            }
            if (held->start_sample != start_sample || held->duration_samples != duration) {
                throw std::runtime_error(case_name + ": sample span mismatch");
            }
            if (held->magnitude.size() != cells.size() - 6) {
                throw std::runtime_error(case_name + ": bin count " + std::to_string(held->magnitude.size()) +
                                         " expected " + std::to_string(cells.size() - 6));
            }
            for (std::size_t bin = 0; bin < held->magnitude.size(); ++bin) {
                const double expected = std::stod(cells[6 + bin]);
                const double error = std::abs(held->magnitude[bin] - expected);
                max_error = std::max(max_error, error);
                if (error > 1e-12) {
                    throw std::runtime_error(case_name + " bin " + std::to_string(bin) + ": " +
                                             std::to_string(held->magnitude[bin]) + " expected " +
                                             std::to_string(expected));
                }
            }
            held.reset();
            ++out_count;
        };
        auto finish_case = [&]() {
            if (!monitor.has_value()) {
                return;
            }
            if (held.has_value()) {
                throw std::runtime_error(case_name + ": engine produced an interval with no matching out row");
            }
            // Java's trailing flush was already consumed by its out row, so
            // a second flush here must yield nothing.
            if (monitor->flush().has_value()) {
                throw std::runtime_error(case_name + ": engine flush produced an interval the reference did not");
            }
        };

        std::string line;
        while (std::getline(input, line)) {
            while (!line.empty() && (line.back() == '\r' || line.back() == '\n')) {
                line.pop_back();
            }
            if (line.empty() || line[0] == '#') {
                continue;
            }
            const auto cells = split(line);
            if (cells[0] == "case") {
                finish_case();
                case_name = cells[1];
                LtsaConfig config;
                config.enabled = true;
                config.interval_seconds = std::stoi(cells[2]);
                monitor.emplace(config);
                ++case_count;
            }
            else if (cells[0] == "in") {
                if (held.has_value()) {
                    throw std::runtime_error(case_name + ": engine produced an interval with no matching out row");
                }
                const auto time_ms = static_cast<std::int64_t>(std::stoll(cells[1]));
                const auto start_sample = static_cast<std::int64_t>(std::stoll(cells[2]));
                const auto duration = static_cast<std::int64_t>(std::stoll(cells[3]));
                // Interleaved re/im pairs; magsq exactly as ComplexArray does.
                std::vector<double> magsq;
                magsq.reserve((cells.size() - 4) / 2);
                for (std::size_t i = 4; i + 1 < cells.size(); i += 2) {
                    const double re = std::stod(cells[i]);
                    const double im = std::stod(cells[i + 1]);
                    magsq.push_back(re * re + im * im);
                }
                ++in_count;
                held = monitor->process_frame(time_ms, start_sample, duration, magsq);
            }
            else if (cells[0] == "out") {
                if (!held.has_value()) {
                    // The case's trailing flush.
                    held = monitor->flush();
                }
                check_held(cells);
            }
        }
        finish_case();

        std::cout << "ltsa fixture parity: cases=" << case_count << " in=" << in_count
                  << " out=" << out_count << " maxError=" << max_error << "\n";
        return 0;
    }
    catch (const std::exception& error) {
        std::cerr << "ltsa_fixture_check failed: " << error.what() << "\n";
        return 1;
    }
}
