#include <cmath>
#include <fstream>
#include <iostream>
#include <optional>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include "pamguard/detectors/MatchedTemplateClassifier.h"

// Replays the matched-template classifier fixture generated by
// MatchedTemplateFixtureExporter, which drives the REAL
// MTClassifier.calcCorrelationMatch, ClickLength, restricted-length
// windowing, and normalisation (see the exporter header for the pinned
// quirks). Values compare to a relative tolerance because the reference's
// JTransforms FFTs and the engine's DFT round differently.

namespace {

using pamguard::detectors::MatchedTemplateClassifier;
using pamguard::detectors::MatchedTemplateClassifierConfig;
using pamguard::detectors::MtClassification;

std::vector<std::string> split(const std::string& line) {
    std::vector<std::string> cells;
    std::stringstream stream(line);
    std::string cell;
    while (std::getline(stream, cell, ',')) {
        cells.push_back(cell);
    }
    return cells;
}

std::vector<double> values_from(const std::vector<std::string>& cells, std::size_t start) {
    std::vector<double> values;
    values.reserve(cells.size() - start);
    for (std::size_t i = start; i < cells.size(); ++i) {
        values.push_back(std::stod(cells[i]));
    }
    return values;
}

void check_value(const std::string& context, double actual, double expected, double& max_error) {
    if (std::isnan(expected) || std::isnan(actual)) {
        if (std::isnan(expected) != std::isnan(actual)) {
            throw std::runtime_error(context + ": NaN mismatch (" + std::to_string(actual) +
                                     " vs " + std::to_string(expected) + ")");
        }
        return;
    }
    const double error = std::abs(actual - expected) / std::max(1e-6, std::abs(expected));
    max_error = std::max(max_error, error);
    if (error > 1e-8) {
        throw std::runtime_error(context + ": " + std::to_string(actual) + " expected " +
                                 std::to_string(expected));
    }
}

} // namespace

int main(int argc, char** argv) {
    if (argc != 2) {
        std::cerr << "Usage: matched_template_fixture_check <fixture.csv>\n";
        return 2;
    }

    try {
        std::ifstream input(argv[1]);
        if (!input) {
            throw std::runtime_error(std::string("could not open fixture: ") + argv[1]);
        }

        std::string case_name;
        double sample_rate = 0.0;
        MatchedTemplateClassifierConfig config;
        std::optional<MatchedTemplateClassifier> classifier;
        std::vector<std::vector<double>> waves;
        std::vector<std::vector<double>> expected_results;
        std::size_t case_count = 0;
        std::size_t click_count = 0;
        std::size_t result_count = 0;
        double max_error = 0.0;

        std::string line;
        while (std::getline(input, line)) {
            while (!line.empty() && (line.back() == '\r' || line.back() == '\n')) {
                line.pop_back();
            }
            if (line.empty() || line[0] == '#') {
                continue;
            }
            const auto cells = split(line);
            if (cells[0] == "case") {
                case_name = cells[1];
                sample_rate = std::stod(cells[2]);
                config = MatchedTemplateClassifierConfig{};
                config.enabled = true;
                config.normalisation_type = std::stoi(cells[3]);
                config.peak_search = cells[4] == "1";
                config.peak_smoothing = std::stoi(cells[5]);
                config.length_db = std::stod(cells[6]);
                config.restricted_bins = std::stoi(cells[7]);
                config.channel_classification = std::stoi(cells[8]);
                classifier.reset();
                waves.clear();
                expected_results.clear();
                ++case_count;
            }
            else if (cells[0] == "template") {
                const auto idx = static_cast<std::size_t>(std::stoul(cells[1]));
                if (config.classifiers.size() <= idx) {
                    config.classifiers.resize(idx + 1);
                }
                config.classifiers[idx].threshold_to_accept = std::stod(cells[2]);
                config.classifiers[idx].match_template.sample_rate_hz = std::stod(cells[3]);
                config.classifiers[idx].reject_template.sample_rate_hz = std::stod(cells[4]);
            }
            else if (cells[0] == "tmatch") {
                const auto idx = static_cast<std::size_t>(std::stoul(cells[1]));
                config.classifiers[idx].match_template.waveform = values_from(cells, 2);
            }
            else if (cells[0] == "treject") {
                const auto idx = static_cast<std::size_t>(std::stoul(cells[1]));
                config.classifiers[idx].reject_template.waveform = values_from(cells, 2);
            }
            else if (cells[0] == "click") {
                waves.clear();
                expected_results.clear();
            }
            else if (cells[0] == "wave") {
                waves.push_back(values_from(cells, 2));
            }
            else if (cells[0] == "result") {
                expected_results.push_back(values_from(cells, 1));
            }
            else if (cells[0] == "classified") {
                if (!classifier.has_value()) {
                    // Zeroed reject templates are the reference's "none"
                    // path; the engine's empty-waveform guard must not
                    // reject them, so name them to keep valid() happy.
                    for (auto& pair : config.classifiers) {
                        pair.match_template.name = "match";
                        pair.reject_template.name = "reject";
                    }
                    classifier.emplace(sample_rate, config);
                    if (!classifier->valid()) {
                        throw std::runtime_error(case_name + ": classifier invalid: " +
                                                 classifier->invalid_reason());
                    }
                }
                const MtClassification outcome = classifier->classify(waves);
                if (outcome.best_results.size() != expected_results.size()) {
                    throw std::runtime_error(case_name + ": classifier count mismatch");
                }
                for (const auto& expected : expected_results) {
                    const auto idx = static_cast<std::size_t>(expected[0]);
                    const auto& actual = outcome.best_results[idx];
                    check_value(case_name + " threshold[" + std::to_string(idx) + "]",
                                actual.threshold, expected[1], max_error);
                    check_value(case_name + " matchCorr[" + std::to_string(idx) + "]",
                                actual.match_corr, expected[2], max_error);
                    check_value(case_name + " rejectCorr[" + std::to_string(idx) + "]",
                                actual.reject_corr, expected[3], max_error);
                    ++result_count;
                }
                const bool expected_flag = cells[1] == "1";
                if (outcome.classified != expected_flag) {
                    throw std::runtime_error(case_name + ": classified " +
                                             (outcome.classified ? "true" : "false") + " expected " +
                                             (expected_flag ? "true" : "false"));
                }
                ++click_count;
            }
        }

        std::cout << "matched-template fixture parity: cases=" << case_count
                  << " clicks=" << click_count << " results=" << result_count
                  << " maxRelError=" << max_error << "\n";
        return 0;
    }
    catch (const std::exception& error) {
        std::cerr << "matched_template_fixture_check failed: " << error.what() << "\n";
        return 1;
    }
}
