#include <cmath>
#include <cstdint>
#include <deque>
#include <fstream>
#include <iostream>
#include <optional>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include "pamguard/detectors/IshmaelDetector.h"
#include "pamguard/detectors/MatchFiltDetector.h"

// Replays the Ishmael matched-filter fixture generated by
// MatchFiltFixtureExporter (REAL MatchFiltProcess2 + IshPeakProcess, with
// the kernel round-tripped through a real WAV file). The exported kernel is
// the 16-bit read-back, so both sides run identical doubles. Multi-sample
// detection-function blocks pin the peak picker's per-sample walk.

namespace {

using pamguard::detectors::IshmaelDetection;
using pamguard::detectors::IshmaelEnergySumConfig;
using pamguard::detectors::IshmaelPeakPicker;
using pamguard::detectors::MatchFiltConfig;
using pamguard::detectors::MatchFiltDetector;

std::vector<std::string> split(const std::string& line) {
    std::vector<std::string> cells;
    std::stringstream stream(line);
    std::string cell;
    while (std::getline(stream, cell, ',')) {
        cells.push_back(cell);
    }
    return cells;
}

std::vector<double> values_from(const std::vector<std::string>& cells, std::size_t start) {
    std::vector<double> values;
    values.reserve(cells.size() - start);
    for (std::size_t i = start; i < cells.size(); ++i) {
        values.push_back(std::stod(cells[i]));
    }
    return values;
}

void check_close(const std::string& context, double actual, double expected, double& max_error) {
    const double error = std::abs(actual - expected) / std::max(1.0, std::abs(expected));
    max_error = std::max(max_error, error);
    if (error > 1e-9) {
        throw std::runtime_error(context + ": " + std::to_string(actual) + " expected " +
                                 std::to_string(expected));
    }
}

} // namespace

int main(int argc, char** argv) {
    if (argc != 2) {
        std::cerr << "Usage: match_filt_fixture_check <fixture.csv>\n";
        return 2;
    }

    try {
        std::ifstream input(argv[1]);
        if (!input) {
            throw std::runtime_error(std::string("could not open fixture: ") + argv[1]);
        }

        std::string case_name;
        double sample_rate = 0.0;
        MatchFiltConfig config;
        std::optional<MatchFiltDetector> detector;
        std::optional<IshmaelPeakPicker> picker;
        std::deque<MatchFiltDetector::FnBlock> produced_blocks;
        std::deque<IshmaelDetection> produced_dets;
        std::size_t case_count = 0;
        std::size_t in_count = 0;
        std::size_t block_count = 0;
        std::size_t fn_values = 0;
        std::size_t det_count = 0;
        double max_error = 0.0;

        auto finish_case = [&]() {
            if (!produced_blocks.empty()) {
                throw std::runtime_error(case_name + ": engine produced unmatched fn blocks");
            }
            if (!produced_dets.empty()) {
                throw std::runtime_error(case_name + ": engine produced unmatched detections");
            }
        };

        std::string line;
        while (std::getline(input, line)) {
            while (!line.empty() && (line.back() == '\r' || line.back() == '\n')) {
                line.pop_back();
            }
            if (line.empty() || line[0] == '#') {
                continue;
            }
            const auto cells = split(line);
            if (cells[0] == "case") {
                finish_case();
                case_name = cells[1];
                sample_rate = std::stod(cells[2]);
                config = MatchFiltConfig{};
                config.enabled = true;
                config.thresh = std::stod(cells[4]);
                config.min_time_s = std::stod(cells[5]);
                config.max_time_s = std::stod(cells[6]);
                config.refractory_time_s = std::stod(cells[7]);
                detector.reset();
                picker.reset();
                ++case_count;
            }
            else if (cells[0] == "kernelwave") {
                config.kernel = values_from(cells, 1);
                detector.emplace(sample_rate, config);
                IshmaelEnergySumConfig picker_config;
                picker_config.thresh = config.thresh;
                picker_config.min_time_s = config.min_time_s;
                picker_config.max_time_s = config.max_time_s;
                picker_config.refractory_time_s = config.refractory_time_s;
                picker_config.f0 = 0.0;
                picker_config.f1 = sample_rate / 2.0;
                // The matched filter's detection rate is the AUDIO rate
                // (getDetSampleRate returns getSampleRate), so hop 1.
                picker.emplace(sample_rate, 1, picker_config);
            }
            else if (cells[0] == "prep") {
                if (detector->fft_length() != static_cast<std::size_t>(std::stoul(cells[1])) ||
                    detector->useful_samples() != static_cast<std::size_t>(std::stoul(cells[2]))) {
                    throw std::runtime_error(case_name + ": fftLength/usefulSamples mismatch (got " +
                                             std::to_string(detector->fft_length()) + "/" +
                                             std::to_string(detector->useful_samples()) + ")");
                }
                check_close(case_name + " normConst", detector->norm_const(), std::stod(cells[3]), max_error);
            }
            else if (cells[0] == "in") {
                const auto samples = values_from(cells, 2);
                auto blocks = detector->process(0, samples);
                for (auto& block : blocks) {
                    produced_blocks.push_back(std::move(block));
                }
                ++in_count;
            }
            else if (cells[0] == "fnblock") {
                if (produced_blocks.empty()) {
                    throw std::runtime_error(case_name + ": reference produced a block, engine did not");
                }
                const auto block = std::move(produced_blocks.front());
                produced_blocks.pop_front();
                if (block.start_sample != std::stoll(cells[1])) {
                    throw std::runtime_error(case_name + ": block startSample " +
                                             std::to_string(block.start_sample) + " expected " + cells[1]);
                }
                if (block.values.size() != cells.size() - 2) {
                    throw std::runtime_error(case_name + ": block length mismatch");
                }
                for (std::size_t i = 0; i < block.values.size(); ++i) {
                    check_close(case_name + " fn[" + std::to_string(i) + "]",
                                block.values[i], std::stod(cells[i + 2]), max_error);
                    ++fn_values;
                    auto det = picker->process(0, block.start_sample + static_cast<std::int64_t>(i),
                                               block.values[i]);
                    if (det.has_value()) {
                        produced_dets.push_back(*det);
                    }
                }
                ++block_count;
            }
            else if (cells[0] == "detection") {
                if (produced_dets.empty()) {
                    throw std::runtime_error(case_name + ": engine produced no detection for a detection row");
                }
                const auto det = produced_dets.front();
                produced_dets.pop_front();
                if (det.channel != static_cast<std::size_t>(std::stoul(cells[1])) ||
                    det.start_sample != std::stoll(cells[2]) ||
                    det.duration_samples != std::stoll(cells[3]) ||
                    det.peak_time_sample != std::stoll(cells[4])) {
                    throw std::runtime_error(case_name + ": detection sample fields mismatch");
                }
                check_close(case_name + " peakHeight", det.peak_height, std::stod(cells[5]), max_error);
                if (det.start_time_ms != std::stoll(cells[6])) {
                    throw std::runtime_error(case_name + ": startMsec mismatch");
                }
                check_close(case_name + " lowFreq", det.low_freq_hz, std::stod(cells[7]), max_error);
                check_close(case_name + " highFreq", det.high_freq_hz, std::stod(cells[8]), max_error);
                ++det_count;
            }
        }
        finish_case();

        std::cout << "match-filt fixture parity: cases=" << case_count << " in=" << in_count
                  << " blocks=" << block_count << " fnValues=" << fn_values
                  << " detections=" << det_count << " maxRelError=" << max_error << "\n";
        return 0;
    }
    catch (const std::exception& error) {
        std::cerr << "match_filt_fixture_check failed: " << error.what() << "\n";
        return 1;
    }
}
