#include <array>
#include <cmath>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <optional>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include "pamguard/detectors/IshmaelDetector.h"
#include "pamguard/detectors/SgramCorrDetector.h"

// Replays the Ishmael spectrogram-correlation fixture generated by
// SgramCorrFixtureExporter (REAL SgramCorrProcess + IshPeakProcess). The
// exported kernel rows are compared against the engine's kernel directly,
// then the FFT-slice stream is replayed through the detector and the
// shared peak picker.

namespace {

using pamguard::detectors::IshmaelDetection;
using pamguard::detectors::IshmaelEnergySumConfig;
using pamguard::detectors::IshmaelPeakPicker;
using pamguard::detectors::SgramCorrConfig;
using pamguard::detectors::SgramCorrDetector;

std::vector<std::string> split(const std::string& line) {
    std::vector<std::string> cells;
    std::stringstream stream(line);
    std::string cell;
    while (std::getline(stream, cell, ',')) {
        cells.push_back(cell);
    }
    return cells;
}

void check_close(const std::string& context, double actual, double expected, double& max_error) {
    const double error = std::abs(actual - expected) / std::max(1.0, std::abs(expected));
    max_error = std::max(max_error, error);
    if (error > 1e-9) {
        throw std::runtime_error(context + ": " + std::to_string(actual) + " expected " +
                                 std::to_string(expected));
    }
}

} // namespace

int main(int argc, char** argv) {
    if (argc != 2) {
        std::cerr << "Usage: sgram_corr_fixture_check <fixture.csv>\n";
        return 2;
    }

    try {
        std::ifstream input(argv[1]);
        if (!input) {
            throw std::runtime_error(std::string("could not open fixture: ") + argv[1]);
        }

        std::string case_name;
        double sample_rate = 0.0;
        std::size_t fft_length = 0;
        std::size_t fft_hop = 0;
        SgramCorrConfig config;
        std::optional<SgramCorrDetector> detector;
        std::optional<IshmaelPeakPicker> picker;
        std::optional<double> fn_pending;
        std::size_t pending_channel = 0;
        std::int64_t pending_start_sample = 0;
        std::optional<IshmaelDetection> det_pending;
        std::size_t case_count = 0;
        std::size_t kernel_values = 0;
        std::size_t in_count = 0;
        std::size_t fn_count = 0;
        std::size_t det_count = 0;
        double max_error = 0.0;

        auto build = [&]() {
            detector.emplace(sample_rate, fft_length, fft_hop, config);
            IshmaelEnergySumConfig picker_config;
            picker_config.thresh = config.thresh;
            picker_config.min_time_s = config.min_time_s;
            picker_config.max_time_s = config.max_time_s;
            picker_config.refractory_time_s = config.refractory_time_s;
            picker_config.f0 = detector->min_frequency_hz();
            picker_config.f1 = detector->max_frequency_hz();
            picker.emplace(sample_rate, fft_hop, picker_config);
        };
        auto finish_case = [&]() {
            if (fn_pending.has_value()) {
                throw std::runtime_error(case_name + ": engine produced an unmatched fn value");
            }
            if (det_pending.has_value()) {
                throw std::runtime_error(case_name + ": engine produced a detection the reference did not");
            }
        };

        std::string line;
        while (std::getline(input, line)) {
            while (!line.empty() && (line.back() == '\r' || line.back() == '\n')) {
                line.pop_back();
            }
            if (line.empty() || line[0] == '#') {
                continue;
            }
            const auto cells = split(line);
            if (cells[0] == "case") {
                finish_case();
                case_name = cells[1];
                sample_rate = std::stod(cells[2]);
                fft_length = static_cast<std::size_t>(std::stoul(cells[3]));
                fft_hop = static_cast<std::size_t>(std::stoul(cells[4]));
                config = SgramCorrConfig{};
                config.enabled = true;
                config.spread = std::stod(cells[5]);
                config.use_log = cells[6] == "1";
                config.thresh = std::stod(cells[7]);
                config.min_time_s = std::stod(cells[8]);
                config.max_time_s = std::stod(cells[9]);
                config.refractory_time_s = std::stod(cells[10]);
                detector.reset();
                picker.reset();
                ++case_count;
            }
            else if (cells[0] == "segment") {
                config.segments.push_back({std::stod(cells[1]), std::stod(cells[2]),
                                           std::stod(cells[3]), std::stod(cells[4])});
            }
            else if (cells[0] == "kernel") {
                build();
                if (detector->bin_offset() != std::stoi(cells[1]) ||
                    detector->kernel_length() != static_cast<std::size_t>(std::stoul(cells[2])) ||
                    detector->kernel_bins() != static_cast<std::size_t>(std::stoul(cells[3]))) {
                    throw std::runtime_error(case_name + ": kernel shape mismatch (got offset " +
                                             std::to_string(detector->bin_offset()) + " " +
                                             std::to_string(detector->kernel_length()) + "x" +
                                             std::to_string(detector->kernel_bins()) + ")");
                }
                check_close(case_name + " loFreq",
                            static_cast<float>(detector->min_frequency_hz()), std::stod(cells[4]), max_error);
                check_close(case_name + " hiFreq",
                            static_cast<float>(detector->max_frequency_hz()), std::stod(cells[5]), max_error);
            }
            else if (cells[0] == "kernelrow") {
                const auto row = static_cast<std::size_t>(std::stoul(cells[1]));
                const auto& kernel = detector->kernel();
                if (cells.size() - 2 != kernel[row].size()) {
                    throw std::runtime_error(case_name + ": kernel row width mismatch");
                }
                for (std::size_t j = 0; j + 2 < cells.size(); ++j) {
                    check_close(case_name + " kernel[" + std::to_string(row) + "][" + std::to_string(j) + "]",
                                kernel[row][j], std::stod(cells[j + 2]), max_error);
                    ++kernel_values;
                }
            }
            else if (cells[0] == "in") {
                if (fn_pending.has_value() || det_pending.has_value()) {
                    throw std::runtime_error(case_name + ": engine output never matched before next slice");
                }
                pending_channel = static_cast<std::size_t>(std::stoul(cells[1]));
                pending_start_sample = std::stoll(cells[2]);
                std::vector<double> magsq;
                magsq.reserve((cells.size() - 3) / 2);
                for (std::size_t i = 3; i + 1 < cells.size(); i += 2) {
                    const double re = std::stod(cells[i]);
                    const double im = std::stod(cells[i + 1]);
                    magsq.push_back(re * re + im * im);
                }
                fn_pending = detector->process_frame(pending_channel, magsq);
                ++in_count;
            }
            else if (cells[0] == "fn") {
                if (!fn_pending.has_value()) {
                    throw std::runtime_error(case_name + ": reference produced an fn value, engine did not");
                }
                check_close(case_name + " fn", *fn_pending, std::stod(cells[1]), max_error);
                det_pending = picker->process(pending_channel, pending_start_sample, *fn_pending);
                fn_pending.reset();
                ++fn_count;
            }
            else if (cells[0] == "detection") {
                if (!det_pending.has_value()) {
                    throw std::runtime_error(case_name + ": engine produced no detection for a detection row");
                }
                if (det_pending->channel != static_cast<std::size_t>(std::stoul(cells[1])) ||
                    det_pending->start_sample != std::stoll(cells[2]) ||
                    det_pending->duration_samples != std::stoll(cells[3]) ||
                    det_pending->peak_time_sample != std::stoll(cells[4])) {
                    throw std::runtime_error(case_name + ": detection sample fields mismatch");
                }
                check_close(case_name + " peakHeight", det_pending->peak_height, std::stod(cells[5]), max_error);
                if (det_pending->start_time_ms != std::stoll(cells[6])) {
                    throw std::runtime_error(case_name + ": startMsec mismatch");
                }
                check_close(case_name + " lowFreq", det_pending->low_freq_hz, std::stod(cells[7]), max_error);
                check_close(case_name + " highFreq", det_pending->high_freq_hz, std::stod(cells[8]), max_error);
                det_pending.reset();
                ++det_count;
            }
        }
        finish_case();

        std::cout << "sgram-corr fixture parity: cases=" << case_count
                  << " kernelValues=" << kernel_values << " in=" << in_count
                  << " fn=" << fn_count << " detections=" << det_count
                  << " maxRelError=" << max_error << "\n";
        return 0;
    }
    catch (const std::exception& error) {
        std::cerr << "sgram_corr_fixture_check failed: " << error.what() << "\n";
        return 1;
    }
}
