#include "pamguard/project/BuiltInControlledUnits.h"

#include <utility>

#include "pamguard/project/AlarmEffortControlledUnits.h"
#include "pamguard/project/AuralListeningControlledUnit.h"
#include "pamguard/project/ClickDetectorControlledUnit.h"
#include "pamguard/project/ClipGeneratorControlledUnit.h"
#include "pamguard/project/FilterDecimatorControlledUnits.h"
#include "pamguard/project/GlobalSettingsAdapters.h"
#include "pamguard/project/IshmaelControlledUnits.h"
#include "pamguard/project/LevelMeterControlledUnit.h"
#include "pamguard/project/MatchedTemplateControlledUnit.h"
#include "pamguard/project/MhtClickTrainControlledUnit.h"
#include "pamguard/project/NoiseLtsaControlledUnits.h"
#include "pamguard/project/SignalRoutingControlledUnits.h"
#include "pamguard/project/SoundRecorderControlledUnit.h"
#include "pamguard/project/SoundOutputControlledUnit.h"
#include "pamguard/project/UserInputControlledUnit.h"
#include "pamguard/project/WhistleMoanControlledUnit.h"

namespace pamguard::project {

namespace {

std::vector<RunMode> all_java_modes() {
    return {
        RunMode::Normal,
        RunMode::Mixed,
        RunMode::Viewer,
    };
}

InstanceRulesDescriptor unlimited_in_all_modes() {
    return {
        0,
        std::nullopt,
        all_java_modes(),
    };
}

SettingsDescriptor array_manager_settings() {
    return {
        kArrayManagerSettingsVersion,
        {
            "Array.ArrayParameters",
            "Array.PamArray",
            "Array.Streamer",
            "Array.Hydrophone",
        },
        {
            "src/Array/ArrayManager.java",
            "src/Array/ArrayParameters.java",
            "src/Array/PamArray.java",
            "src/Array/Streamer.java",
            "src/Array/Hydrophone.java",
            "src/Array/ArrayDialog.java",
            "src/Array/EnvironmentPanel.java",
        },
        R"({"arrayName":"Basic Linear Array","instrumentType":null,"instrumentId":null,"speedOfSoundMps":1500,"speedOfSoundErrorMps":0,"originInterpolation":2,"hydrophoneInterpolation":0,"streamers":[{"id":0,"name":null,"xM":0,"yM":0,"zM":0,"xErrorM":0.1,"yErrorM":0.1,"zErrorM":0.1,"headingDegrees":null,"pitchDegrees":null,"rollDegrees":null,"locatorClass":"Array.ThreadingHydrophoneLocator","originClass":"Array.streamerOrigin.GPSOriginMethod"}],"hydrophones":[{"channel":0,"streamerId":0,"type":"Unknown","xM":0,"yM":0,"zM":-5,"xErrorM":0,"yErrorM":0,"zErrorM":0,"sensitivityDb":-170,"preampGainDb":0,"bandwidthHz":[0,20000]},{"channel":1,"streamerId":0,"type":"Unknown","xM":0,"yM":-3,"zM":-5,"xErrorM":0,"yErrorM":0,"zErrorM":0,"sensitivityDb":-170,"preampGainDb":0,"bandwidthHz":[0,20000]}]})",
        {
            {
                "array-manager.sections",
                {
                    "Instrument Identity",
                    "Environment",
                    "Streamers",
                    "Hydrophone Elements",
                    "Channel Mapping",
                },
            },
        },
        {
            {
                "/arrayName",
                "ArrayManager.createDefaultArray().arrayName",
                R"("Basic Linear Array")",
                {},
                {},
                "Array.ArrayManager#createDefaultArray",
            },
            {
                "/speedOfSoundMps",
                "PamArray.speedOfSound",
                "1500",
                {},
                {},
                "Array.PamArray#speedOfSound",
            },
            {
                "/speedOfSoundErrorMps",
                "PamArray.speedOfSoundError",
                "0",
                {},
                {},
                "Array.PamArray#speedOfSoundError",
            },
            {
                "/originInterpolation",
                "PamArray.originInterpolation",
                "2",
                {},
                {},
                "Array.PamArray#ORIGIN_USE_PRECEEDING",
            },
            {
                "/hydrophoneInterpolation",
                "PamArray.hydrophoneInterpolation",
                "0",
                {},
                {},
                "Array.PamArray#ORIGIN_USE_LATEST",
            },
            {
                "/hydrophones",
                "ArrayManager.createDefaultArray().hydrophones",
                std::nullopt,
                "PamArray.createSimpleArray(\"Basic Linear Array\", 0, -5, 3, 2, -170, 0, [0,20000])",
                {},
                "Array.ArrayManager#createDefaultArray",
            },
            {
                "/streamers",
                "PamArray.checkDefStreamer().streamers",
                std::nullopt,
                "one Streamer(0,0,0,0,0.1,0.1,0.1) created by MasterLocator setup",
                {},
                "Array.PamArray#checkDefStreamer",
            },
        },
        SettingsChangePolicy::StopRequired,
        "not-claimed",
        R"({
            "$schema":"https://json-schema.org/draft/2020-12/schema",
            "type":"object",
            "additionalProperties":false,
            "properties":{
                "arrayName":{"type":"string","minLength":1},
                "instrumentType":{"type":["string","null"]},
                "instrumentId":{"type":["string","null"]},
                "speedOfSoundMps":{"type":"number","exclusiveMinimum":0},
                "speedOfSoundErrorMps":{"type":"number","minimum":0},
                "originInterpolation":{
                    "type":"integer",
                    "minimum":0,
                    "maximum":2
                },
                "hydrophoneInterpolation":{
                    "type":"integer",
                    "minimum":0,
                    "maximum":2
                },
                "streamers":{
                    "type":"array",
                    "minItems":1,
                    "maxItems":32,
                    "items":{
                        "type":"object",
                        "additionalProperties":false,
                        "properties":{
                            "id":{"type":"integer","minimum":0,"maximum":31},
                            "name":{"type":["string","null"]},
                            "xM":{"type":"number"},
                            "yM":{"type":"number"},
                            "zM":{"type":"number"},
                            "xErrorM":{"type":"number","minimum":0},
                            "yErrorM":{"type":"number","minimum":0},
                            "zErrorM":{"type":"number","minimum":0},
                            "headingDegrees":{"type":["number","null"]},
                            "pitchDegrees":{"type":["number","null"]},
                            "rollDegrees":{"type":["number","null"]},
                            "locatorClass":{"type":"string","minLength":1},
                            "originClass":{"type":"string","minLength":1}
                        },
                        "required":[
                            "id","name","xM","yM","zM",
                            "xErrorM","yErrorM","zErrorM",
                            "headingDegrees","pitchDegrees","rollDegrees",
                            "locatorClass","originClass"
                        ]
                    }
                },
                "hydrophones":{
                    "type":"array",
                    "minItems":1,
                    "maxItems":32,
                    "items":{
                        "type":"object",
                        "additionalProperties":false,
                        "properties":{
                            "channel":{"type":"integer","minimum":0,"maximum":31},
                            "streamerId":{"type":"integer","minimum":0,"maximum":31},
                            "type":{"type":"string","minLength":1},
                            "xM":{"type":"number"},
                            "yM":{"type":"number"},
                            "zM":{"type":"number"},
                            "xErrorM":{"type":"number","minimum":0},
                            "yErrorM":{"type":"number","minimum":0},
                            "zErrorM":{"type":"number","minimum":0},
                            "sensitivityDb":{"type":"number"},
                            "preampGainDb":{"type":"number"},
                            "bandwidthHz":{
                                "type":"array",
                                "minItems":2,
                                "maxItems":2,
                                "items":{"type":"number","minimum":0}
                            }
                        },
                        "required":[
                            "channel","streamerId","type",
                            "xM","yM","zM",
                            "xErrorM","yErrorM","zErrorM",
                            "sensitivityDb","preampGainDb","bandwidthHz"
                        ]
                    }
                }
            },
            "required":[
                "arrayName","instrumentType","instrumentId",
                "speedOfSoundMps","speedOfSoundErrorMps",
                "originInterpolation","hydrophoneInterpolation",
                "streamers","hydrophones"
            ],
            "x-pamguardConstraints":[
                {
                    "id":"streamer-ids-match-list-order",
                    "kind":"index-equals-field",
                    "arrayPointer":"/streamers",
                    "field":"id"
                },
                {
                    "id":"hydrophone-channels-match-list-order",
                    "kind":"index-equals-field",
                    "arrayPointer":"/hydrophones",
                    "field":"channel"
                },
                {
                    "id":"hydrophone-streamers-exist",
                    "kind":"array-index-reference",
                    "arrayPointer":"/hydrophones",
                    "field":"streamerId",
                    "targetArrayPointer":"/streamers"
                },
                {
                    "id":"hydrophone-bandwidth-ordered",
                    "kind":"ordered-pair-per-item",
                    "arrayPointer":"/hydrophones",
                    "field":"bandwidthHz"
                }
            ]
        })",
    };
}

SettingsDescriptor acquisition_settings() {
    return {
        1,
        {"Acquisition.AcquisitionParameters"},
        {
            "src/Acquisition/AcquisitionControl.java",
            "src/Acquisition/AcquisitionParameters.java",
            "src/Acquisition/AcquisitionDialog.java",
            "src/Acquisition/layoutFX/AcquisitionPaneFX.java",
        },
        R"({"daqSystemType":"Sound Card","sampleRate":48000,"nChannels":2,"hardwareChannelList":[0,1],"hydrophoneList":[0,1],"voltsPeak2Peak":5,"preamplifier":{"gainDb":0,"bandwidthHz":[0,20000]},"subtractDC":true,"dcTimeConstantSeconds":1,"calibrationDbOffsetByChannel":[]})",
        {
            {
                "settings.normal",
                {
                    "Data Source Type",
                    "Device-specific settings",
                    "Sampling",
                    "Channel mapping",
                    "Calibration",
                },
            },
            {
                "settings.viewer-tabs",
                {
                    "Offline Files",
                    "DAQ Settings",
                },
            },
            {
                "settings.smru-tabs",
                {
                    "DAQ Settings",
                    "GPS Timing",
                },
            },
        },
        {
            {
                "/daqSystemType",
                "daqSystemType",
                R"("Sound Card")",
                {},
                {},
                "Acquisition.AcquisitionParameters#daqSystemType",
            },
            {
                "/sampleRate",
                "sampleRate",
                "48000",
                {},
                {},
                "Acquisition.AcquisitionParameters#sampleRate",
            },
            {
                "/nChannels",
                "nChannels",
                "2",
                {},
                {},
                "Acquisition.AcquisitionParameters#nChannels",
            },
            {
                "/voltsPeak2Peak",
                "voltsPeak2Peak",
                "5",
                {},
                {},
                "Acquisition.AcquisitionParameters#voltsPeak2Peak",
            },
            {
                "/hardwareChannelList",
                "channelList",
                "[0,1]",
                {},
                {},
                "Acquisition.AcquisitionParameters#getHardwareChannelList",
            },
            {
                "/hydrophoneList",
                "hydrophoneList",
                "[0,1]",
                {},
                {},
                "Acquisition.AcquisitionParameters#getHydrophoneList",
            },
            {
                "/preamplifier",
                "preamplifier",
                R"({"gainDb":0,"bandwidthHz":[0,20000]})",
                {},
                {},
                "Acquisition.AcquisitionParameters#preamplifier",
            },
            {
                "/subtractDC",
                "subtractDC",
                "true",
                {},
                {},
                "Acquisition.AcquisitionParameters#subtractDC",
            },
            {
                "/dcTimeConstantSeconds",
                "dcTimeConstant",
                "1",
                {},
                {},
                "Acquisition.AcquisitionParameters#dcTimeConstant",
            },
        },
        SettingsChangePolicy::StopRequired,
        "not-claimed",
        R"({
            "$schema":"https://json-schema.org/draft/2020-12/schema",
            "type":"object",
            "additionalProperties":false,
            "properties":{
                "daqSystemType":{"type":"string","minLength":1},
                "sampleRate":{"type":"number","exclusiveMinimum":0},
                "nChannels":{"type":"integer","minimum":1,"maximum":32},
                "hardwareChannelList":{
                    "type":"array",
                    "minItems":1,
                    "maxItems":32,
                    "items":{"type":"integer","minimum":0,"maximum":31}
                },
                "hydrophoneList":{
                    "type":"array",
                    "minItems":1,
                    "maxItems":32,
                    "items":{"type":"integer","minimum":0,"maximum":31}
                },
                "voltsPeak2Peak":{"type":"number","exclusiveMinimum":0},
                "preamplifier":{
                    "type":"object",
                    "additionalProperties":false,
                    "properties":{
                        "gainDb":{"type":"number"},
                        "bandwidthHz":{
                            "type":"array",
                            "items":{"type":"number","minimum":0},
                            "minItems":2,
                            "maxItems":2
                        }
                    },
                    "required":["gainDb","bandwidthHz"]
                },
                "subtractDC":{"type":"boolean"},
                "dcTimeConstantSeconds":{
                    "type":"number",
                    "exclusiveMinimum":0
                },
                "calibrationDbOffsetByChannel":{
                    "type":"array",
                    "items":{"type":"number"}
                }
            },
            "required":[
                "daqSystemType",
                "sampleRate",
                "nChannels",
                "hardwareChannelList",
                "hydrophoneList",
                "voltsPeak2Peak",
                "preamplifier",
                "subtractDC",
                "dcTimeConstantSeconds",
                "calibrationDbOffsetByChannel"
            ],
            "x-pamguardConstraints":[
                {
                    "id":"hardware-channels-cover-active-channels",
                    "kind":"count-equals",
                    "arrayPointer":"/hardwareChannelList",
                    "countPointer":"/nChannels"
                },
                {
                    "id":"hydrophones-cover-active-channels",
                    "kind":"count-equals",
                    "arrayPointer":"/hydrophoneList",
                    "countPointer":"/nChannels"
                },
                {
                    "id":"preamplifier-bandwidth-ordered",
                    "kind":"ordered-pair",
                    "pointer":"/preamplifier/bandwidthHz"
                },
                {
                    "id":"calibration-empty-or-covers-channels",
                    "kind":"empty-or-count-equals",
                    "arrayPointer":"/calibrationDbOffsetByChannel",
                    "countPointer":"/nChannels"
                }
            ]
        })",
    };
}

SettingsDescriptor fft_settings() {
    return {
        1,
        {
            "fftManager.FFTParameters",
            "spectrogramNoiseReduction.SpectrogramNoiseSettings",
        },
        {
            "src/fftManager/PamFFTControl.java",
            "src/fftManager/FFTParameters.java",
            "src/fftManager/FFTParametersDialog.java",
            "src/fftManager/layoutFX/FFTPaneFX.java",
        },
        R"({"fft":{"fftLength":1024,"fftHop":512,"channelMap":3,"windowFunction":2,"clickRemoval":false,"clickThreshold":5,"clickPower":6},"spectralNoise":{"medianFilter":false,"medianFilterLength":61,"averageSubtraction":false,"updateConstant":0.02,"kernelSmoothing":false,"threshold":false,"thresholdDb":8.0,"finalOutput":2}})",
        {
            {
                "settings.tabs",
                {
                    "FFT",
                    "Click Removal",
                    "Spectral Noise Removal",
                },
            },
        },
        {
            {
                "/fft/fftLength",
                "fftLength",
                "1024",
                {},
                {},
                "fftManager.FFTParameters#fftLength",
            },
            {
                "/fft/fftHop",
                "fftHop",
                "512",
                {},
                {},
                "fftManager.FFTParameters#fftHop",
            },
            {
                "/fft/channelMap",
                "channelMap",
                "3",
                {},
                {},
                "fftManager.FFTParameters#channelMap",
            },
            {
                "/fft/windowFunction",
                "windowFunction",
                "2",
                {},
                {},
                "Spectrogram.WindowFunction#HANNING",
            },
            {
                "/fft/clickRemoval",
                "clickRemoval",
                "false",
                {},
                {},
                "fftManager.FFTParameters#clickRemoval",
            },
            {
                "/fft/clickThreshold",
                "clickThreshold",
                "5",
                {},
                {},
                "fftManager.FFTParameters#clickThreshold",
            },
            {
                "/fft/clickPower",
                "clickPower",
                "6",
                {},
                {},
                "fftManager.FFTParameters#clickPower",
            },
        },
        SettingsChangePolicy::StopRequired,
        "not-claimed",
        R"({
            "$schema":"https://json-schema.org/draft/2020-12/schema",
            "type":"object",
            "additionalProperties":false,
            "properties":{
                "fft":{
                    "type":"object",
                    "additionalProperties":false,
                    "properties":{
                        "fftLength":{"type":"integer","minimum":2},
                        "fftHop":{"type":"integer","minimum":1},
                        "channelMap":{
                            "type":"integer",
                            "minimum":1,
                            "maximum":4294967295
                        },
                        "windowFunction":{
                            "type":"integer",
                            "minimum":0,
                            "maximum":5
                        },
                        "clickRemoval":{"type":"boolean"},
                        "clickThreshold":{"type":"number"},
                        "clickPower":{
                            "type":"integer",
                            "minimum":2,
                            "multipleOf":2
                        }
                    },
                    "required":[
                        "fftLength",
                        "fftHop",
                        "channelMap",
                        "windowFunction",
                        "clickRemoval",
                        "clickThreshold",
                        "clickPower"
                    ]
                },
                "spectralNoise":{
                    "type":"object",
                    "additionalProperties":false,
                    "properties":{
                        "medianFilter":{"type":"boolean"},
                        "medianFilterLength":{
                            "type":"integer",
                            "minimum":1
                        },
                        "averageSubtraction":{"type":"boolean"},
                        "updateConstant":{
                            "type":"number",
                            "exclusiveMinimum":0,
                            "exclusiveMaximum":1
                        },
                        "kernelSmoothing":{"type":"boolean"},
                        "threshold":{"type":"boolean"},
                        "thresholdDb":{"type":"number"},
                        "finalOutput":{
                            "type":"integer",
                            "minimum":0,
                            "maximum":2
                        }
                    },
                    "required":[
                        "medianFilter",
                        "medianFilterLength",
                        "averageSubtraction",
                        "updateConstant",
                        "kernelSmoothing",
                        "threshold",
                        "thresholdDb",
                        "finalOutput"
                    ]
                }
            },
            "required":["fft","spectralNoise"],
            "x-pamguardConstraints":[
                {
                    "id":"fft-length-power-of-two",
                    "kind":"power-of-two",
                    "pointer":"/fft/fftLength"
                },
                {
                    "id":"fft-hop-within-length",
                    "kind":"less-than-or-equal",
                    "leftPointer":"/fft/fftHop",
                    "rightPointer":"/fft/fftLength"
                }
            ]
        })",
    };
}

SettingsDescriptor user_display_settings() {
    return {
        1,
        {"userDisplay.UserDisplayParameters"},
        {
            "src/userDisplay/UserDisplayControl.java",
            "src/userDisplay/UserDisplayParameters.java",
        },
        "{}",
        {},
        {},
        SettingsChangePolicy::StopRequired,
        "not-claimed",
        R"({
            "$schema":"https://json-schema.org/draft/2020-12/schema",
            "type":"object",
            "additionalProperties":false,
            "maxProperties":0
        })",
    };
}

SettingsDescriptor spectrogram_settings() {
    return {
        2,
        {"Spectrogram.SpectrogramParameters"},
        {
            "src/Spectrogram/SpectrogramDiplayProvider.java",
            "src/Spectrogram/SpectrogramParameters.java",
            "src/Spectrogram/SpectrogramParamsDialog.java",
        },
        R"({"nPanels":1,"channelList":[0],"frequencyLimits":[0,0],"amplitudeLimits":[50,120],"colourMap":"GREY","wrapDisplay":true,"timeScaleFixed":false,"displayLength":20,"pixelsPerSlics":1,"showScale":true})",
        {
            {
                "spectrogram-settings.tabs",
                {
                    "Data Source",
                    "Scales",
                    "Plug ins",
                    "Mark Observers",
                },
            },
            {
                "spectrogram-scales.sections",
                {
                    "Frequency Range",
                    "Amplitude Range",
                    "Time Range",
                    "Scrolling",
                },
            },
        },
        {
            {
                "/nPanels",
                "nPanels",
                std::nullopt,
                "Array.ArrayManager current hydrophone count",
                {},
                "Spectrogram.SpectrogramParameters#nPanels",
            },
            {
                "/channelList",
                "channelList",
                "[0]",
                {},
                "portable settings retain only the active panel entries",
                "Spectrogram.SpectrogramParameters#channelList",
            },
            {
                "/frequencyLimits",
                "frequencyLimits",
                "[0,0]",
                {},
                {},
                "Spectrogram.SpectrogramParameters#frequencyLimits",
            },
            {
                "/amplitudeLimits",
                "amplitudeLimits",
                "[50,120]",
                {},
                "default underwater scale before the global-medium air override",
                "Spectrogram.SpectrogramParameters#amplitudeLimits",
            },
            {
                "/colourMap",
                "colourMap",
                R"("GREY")",
                {},
                {},
                "Spectrogram.SpectrogramParameters#getColourMap",
            },
            {
                "/wrapDisplay",
                "wrapDisplay",
                "true",
                {},
                {},
                "Spectrogram.SpectrogramParameters#wrapDisplay",
            },
            {
                "/timeScaleFixed",
                "timeScaleFixed",
                "false",
                {},
                {},
                "Spectrogram.SpectrogramParameters#timeScaleFixed",
            },
            {
                "/displayLength",
                "displayLength",
                "20",
                {},
                {},
                "Spectrogram.SpectrogramParameters#displayLength",
            },
            {
                "/pixelsPerSlics",
                "pixelsPerSlics",
                "1",
                {},
                {},
                "Spectrogram.SpectrogramParameters#pixelsPerSlics",
            },
            {
                "/showScale",
                "showScale",
                "true",
                {},
                {},
                "Spectrogram.SpectrogramParameters#showScale",
            },
        },
        SettingsChangePolicy::StopRequired,
        "not-claimed",
        R"({
            "$schema":"https://json-schema.org/draft/2020-12/schema",
            "type":"object",
            "additionalProperties":false,
            "properties":{
                "nPanels":{
                    "type":"integer",
                    "minimum":1,
                    "maximum":32
                },
                "channelList":{
                    "type":"array",
                    "minItems":1,
                    "maxItems":32,
                    "items":{
                        "type":"integer",
                        "minimum":0,
                        "maximum":31
                    }
                },
                "frequencyLimits":{
                    "type":"array",
                    "minItems":2,
                    "maxItems":2,
                    "items":{"type":"number","minimum":0}
                },
                "amplitudeLimits":{
                    "type":"array",
                    "minItems":2,
                    "maxItems":2,
                    "items":{"type":"number"}
                },
                "colourMap":{
                    "type":"string",
                    "enum":[
                        "GREY",
                        "REVERSEGREY",
                        "BLUE",
                        "GREEN",
                        "RED",
                        "HOT",
                        "HSV",
                        "FIRE",
                        "PATRIOTIC"
                    ]
                },
                "wrapDisplay":{"type":"boolean"},
                "timeScaleFixed":{"type":"boolean"},
                "displayLength":{
                    "type":"number",
                    "exclusiveMinimum":0
                },
                "pixelsPerSlics":{
                    "type":"integer",
                    "minimum":1
                },
                "showScale":{"type":"boolean"}
            },
            "required":[
                "nPanels",
                "channelList",
                "frequencyLimits",
                "amplitudeLimits",
                "colourMap",
                "wrapDisplay",
                "timeScaleFixed",
                "displayLength",
                "pixelsPerSlics",
                "showScale"
            ],
            "x-pamguardConstraints":[
                {
                    "id":"panel-channel-count",
                    "kind":"array-length-equals",
                    "pointer":"/channelList",
                    "valuePointer":"/nPanels"
                },
                {
                    "id":"frequency-limits-ordered",
                    "kind":"ordered-pair",
                    "pointer":"/frequencyLimits"
                },
                {
                    "id":"amplitude-limits-ordered",
                    "kind":"ordered-pair",
                    "pointer":"/amplitudeLimits"
                }
            ]
        })",
    };
}

ControlledUnitDescriptor acquisition_descriptor() {
    return {
        "pamguard.acquisition",
        1,
        {
            "Sound Acquisition",
            "Sound Processing",
            "Acquisition.AcquisitionControl",
            "direct",
            "Controls input of sound data from sound cards, NI cards, etc.",
            "sound_processing/AcquisitionHelp/docs/AcquisitionOverview.html",
            {
                "src/PamModel/PamModel.java",
                "src/Acquisition/AcquisitionControl.java",
            },
        },
        unlimited_in_all_modes(),
        {
            {
                "rawAudio",
                "Raw audio",
                DataRoleDirection::Output,
                "pamguard.raw-audio",
                RoleCardinality::ExactlyOne,
                {"sampled", "realtime"},
                {},
                std::nullopt,
            },
        },
        acquisition_settings(),
        {
            1,
            {
                {
                    "acquisition",
                    "pamguard.acquisition",
                    {
                        "",
                        "pamguard.acquisition-settings.v1",
                    },
                    true,
                    AvailabilityStatus::Available,
                    "partial",
                },
            },
            {
                {
                    "rawAudio",
                    {
                        "acquisition",
                        "audio",
                    },
                },
            },
            {},
            {},
            "pamguard.acquisition.runtime",
        },
        AvailabilityStatus::Available,
        "partial",
    };
}

ControlledUnitDescriptor fft_descriptor() {
    return {
        "pamguard.fft",
        1,
        {
            "FFT (Spectrogram) Engine",
            "Sound Processing",
            "fftManager.PamFFTControl",
            "direct",
            "Computes spectrograms of audio data",
            "sound_processing/fftManagerHelp/docs/FFTEngine_Overview.html",
            {
                "src/PamModel/PamModel.java",
                "src/fftManager/PamFFTControl.java",
            },
        },
        unlimited_in_all_modes(),
        {
            {
                "rawAudio",
                "Raw audio source",
                DataRoleDirection::Input,
                "pamguard.raw-audio",
                RoleCardinality::ExactlyOne,
                {"sampled"},
                "PamDetection.RawDataUnit",
                "pamguard.acquisition",
            },
            {
                "fft",
                "FFT data",
                DataRoleDirection::Output,
                "pamguard.fft",
                RoleCardinality::ExactlyOne,
                {"frequency-domain"},
                {},
                std::nullopt,
            },
            {
                "noiseReducedFft",
                "Noise-reduced FFT data",
                DataRoleDirection::Output,
                "pamguard.fft",
                RoleCardinality::ExactlyOne,
                {"frequency-domain"},
                {},
                std::nullopt,
            },
        },
        fft_settings(),
        {
            1,
            {
                {
                    "fft-process",
                    "pamguard.fft",
                    {
                        "/fft",
                        "pamguard.fft-settings.v1",
                    },
                    true,
                    AvailabilityStatus::Available,
                    "partial",
                },
                {
                    "spectral-noise",
                    "pamguard.spectrogram-noise",
                    {
                        "/spectralNoise",
                        "identity.v1",
                    },
                    true,
                    AvailabilityStatus::Available,
                    "internal-foundation",
                },
            },
            {
                {
                    "rawAudio",
                    {
                        "fft-process",
                        "input",
                    },
                },
                {
                    "fft",
                    {
                        "fft-process",
                        "fft",
                    },
                },
                {
                    "noiseReducedFft",
                    {
                        "spectral-noise",
                        "output",
                    },
                },
            },
            {
                {
                    "fft-to-spectral-noise",
                    {
                        "fft-process",
                        "fft",
                    },
                    {
                        "spectral-noise",
                        "input",
                    },
                },
            },
            {},
            "pamguard.fft.runtime",
        },
        AvailabilityStatus::Available,
        "partial",
    };
}

ControlledUnitDescriptor user_display_descriptor() {
    return {
        "pamguard.user-display",
        1,
        {
            "User Display",
            "Displays",
            "userDisplay.UserDisplayControl",
            "provider-owner",
            "Creates an empty display panel which the user can add spectrograms and other displays to",
            "displays/userDisplayHelp/docs/userDisplayPanel.html",
            {
                "src/PamModel/PamModel.java",
                "src/userDisplay/UserDisplayControl.java",
            },
        },
        unlimited_in_all_modes(),
        {},
        user_display_settings(),
        {
            1,
            {},
            {},
            {},
            {"pamguard.spectrogram-display"},
            "pamguard.user-display.runtime",
        },
        AvailabilityStatus::Available,
        "partial",
    };
}

DisplayProviderDescriptor spectrogram_provider_descriptor() {
    return {
        "pamguard.spectrogram-display",
        1,
        "Spectrogram Display",
        "Spectrogram.SpectrogramDiplayProvider",
        "Spectrogram.SpectrogramDisplayComponent",
        "pamguard.user-display",
        0,
        std::nullopt,
        true,
        {
            {
                "fft",
                "FFT source",
                DataRoleDirection::Input,
                "pamguard.fft",
                RoleCardinality::ZeroOrOne,
                {"frequency-domain"},
                "fftManager.FFTDataUnit",
                "pamguard.fft",
            },
        },
        spectrogram_settings(),
        {
            "pamguard.spectrogram-display",
            {
                {
                    "fft",
                    "fft",
                },
            },
        },
        AvailabilityStatus::Available,
        "display-foundation",
        {
            "src/userDisplay/UserDisplayControl.java",
            "src/Spectrogram/SpectrogramDiplayProvider.java",
            "src/Spectrogram/SpectrogramParameters.java",
            "src/Spectrogram/SpectrogramParamsDialog.java",
        },
    };
}

GlobalSettingsDescriptor array_manager_descriptor() {
    return {
        std::string(kArrayManagerGlobalSettingsTypeId),
        "Array Manager",
        {
            "Array Manager",
            "System",
            "Array.ArrayManager",
            "global-core",
            "Configures the hydrophone array and environment used by localisation",
            "utilities.hydrophoneArrayManagerHelp.docs.Array_Overview",
            {
                "src/Array/ArrayManager.java",
                "src/Array/PamArray.java",
                "src/Array/Streamer.java",
                "src/Array/Hydrophone.java",
                "src/PamView/PamGui.java",
            },
        },
        array_manager_settings(),
        std::string(kArrayManagerSettingsAdapterId),
        true,
        AvailabilityStatus::Available,
        "partial",
    };
}

} // namespace

void register_builtin_controlled_units(
    ControlledUnitRegistry& registry) {
    registry.register_global_settings(
        array_manager_descriptor());
    registry.register_controlled_unit(acquisition_descriptor());
    registry.register_controlled_unit(
        make_signal_amplifier_controlled_unit_descriptor());
    registry.register_controlled_unit(
        make_patch_panel_controlled_unit_descriptor());
    registry.register_controlled_unit(
        make_standalone_filter_controlled_unit_descriptor());
    registry.register_controlled_unit(
        make_decimator_controlled_unit_descriptor());
    registry.register_controlled_unit(fft_descriptor());
    registry.register_controlled_unit(
        make_fft_noise_monitor_controlled_unit_descriptor());
    registry.register_controlled_unit(
        make_noise_band_monitor_controlled_unit_descriptor());
    registry.register_controlled_unit(
        make_ltsa_controlled_unit_descriptor());
    registry.register_controlled_unit(
        make_whistle_moan_controlled_unit_descriptor());
    registry.register_controlled_unit(
        make_ishmael_energy_sum_controlled_unit_descriptor());
    registry.register_controlled_unit(
        make_ishmael_sgram_corr_controlled_unit_descriptor());
    registry.register_controlled_unit(
        make_ishmael_match_filter_controlled_unit_descriptor());
    registry.register_controlled_unit(
        make_click_detector_controlled_unit_descriptor());
    registry.register_controlled_unit(
        make_mht_click_train_controlled_unit_descriptor());
    registry.register_controlled_unit(
        make_matched_template_controlled_unit_descriptor());
    registry.register_controlled_unit(
        make_sound_recorder_controlled_unit_descriptor());
    registry.register_controlled_unit(
        make_clip_generator_controlled_unit_descriptor());
    registry.register_controlled_unit(
        make_sound_output_controlled_unit_descriptor());
    registry.register_controlled_unit(
        make_level_meter_controlled_unit_descriptor());
    registry.register_controlled_unit(
        make_user_input_controlled_unit_descriptor());
    registry.register_controlled_unit(
        make_aural_listening_controlled_unit_descriptor());
    registry.register_controlled_unit(
        make_alarm_controlled_unit_descriptor());
    registry.register_controlled_unit(
        make_effort_controlled_unit_descriptor());
    registry.register_controlled_unit(user_display_descriptor());
    registry.register_display_provider(
        spectrogram_provider_descriptor());
    registry.register_display_provider(
        make_click_display_provider_descriptor());
    registry.register_display_provider(
        make_level_meter_display_provider_descriptor());
}

} // namespace pamguard::project
